### ISSUE TITLE
It works only with gallery images

### ISSUE THREAD

**Issue by skined90** [naver/android-imagecropview#12]
When I try  to choose an image from the google photos app which is not located on the phone, or any other place on phone which is not gallery, app break up. I've put image view next to image crop view and image is loaded in it, but in image crop view isn't.

**Comment by helloyako** [comment]
@skined90 
Hello :) Thank you for interest about my code.

Sample app can load image in device.

For example, Local uri is "content://media/external/images/media/...."
Whereas, Photo app uri is "content://com.google.android.apps.photos.content.....".
So to load external image, app need other process.

I know reference code. Look this link https://github.com/coomar2841/image-chooser-library/blob/dev/image-chooser-library/src/main/java/com/kbeanie/imagechooser/threads/ImageProcessorThread.java#L121-L156

I use that library in my app.

Was answer able to help you?

If you don't understand, please reopen this issue.

thank you.

**Comment by skined90** [comment]
Thanks for the answer. Do you have some sample code how to use this in onActivityResult?

**Comment by helloyako** [comment]
@skined90 
image-chooser-library provide sample app
look this code (https://github.com/coomar2841/image-chooser-library/blob/dev/app/src/main/java/com/beanie/imagechooserapp/ImageChooserActivity.java#L149-L162)
