### ISSUE TITLE
Height and width are a bit off

### ISSUE THREAD

**Issue by SerjSmor** [naver/android-imagecropview#14]
If you encounter the ImageCropView being a bit off like this (the height diff is different between lower and upper bounds)

issue:
![image](https://cloud.githubusercontent.com/assets/5365944/16595814/9b1f27cc-42f9-11e6-87b7-c90dcfaec261.png)

fix - put it inside a FrameLayout:

![image](https://cloud.githubusercontent.com/assets/5365944/16595772/8753b186-42f9-11e6-9aa9-60ccdfac968b.png)

**Comment by helloyako** [comment]
@serjSmor 
I don't understand your question.
Can you explain in detail?

**Comment by joeytheman** [comment]
The sizing is a bit off. You can see it by placing a camera preview view behind the ImageCropView, taking a picture, and then putting that picture inside the ImageCropView.

**Comment by helloyako** [comment]
if issue were continue, reopen please.
