### ISSUE TITLE
Wrong aspect ratio for transparent zone

### ISSUE THREAD

**Issue by dmitriid8** [naver/android-imagecropview#15]
After setAspectRatio(3, 1) result cropping zone height looks bigger.
As I understand it should working like if width = 600px, height will be 200. Is it right?

Thank you!

**Comment by helloyako** [comment]
@dmitriid8 
First, I'm sorry for too late answer your question

I tested my library, after checked your issue.
However, I can't find any bugs.

original image : 3024 \* 4032
setAspectRatio(3,1)
cropped image : 3024 \* 1008

It's correct

if you have any question, I am aways welcome 😄 

Thank you.
- original image information
  ![device-2016-07-24-145435](https://cloud.githubusercontent.com/assets/5343804/17082170/311d80ac-51af-11e6-8dd2-13c6e09ceb2f.png)
  ![device-2016-07-24-145425](https://cloud.githubusercontent.com/assets/5343804/17082173/4046c048-51af-11e6-8d2c-2e6ec4777d26.png)
- setAspectRatio(3,1) cropped
  ![device-2016-07-24-145152](https://cloud.githubusercontent.com/assets/5343804/17082176/52a18d40-51af-11e6-9723-86c2d3b4105a.png)
  ![device-2016-07-24-145209](https://cloud.githubusercontent.com/assets/5343804/17082177/57cb4a7c-51af-11e6-871a-b9694592dd06.png)
- result cropped file information
  ![device-2016-07-24-145351](https://cloud.githubusercontent.com/assets/5343804/17082181/785e4546-51af-11e6-8dba-35de468f0ce3.png)

**Comment by dmitriid8** [comment]
My image size 5312x2988. 
My actions queue is:
setAspectRatio(3,1);
setImageURI("uri to file from camera");
getCroppedImage();

As result I get image 5312x1411, but should 5312x1770.

Do you have idea what may be wrong? 
![screenshot_2016-07-25-10-08-59](https://cloud.githubusercontent.com/assets/15122249/17089600/9c005ee6-5252-11e6-8345-28e6b5b2c4a6.jpg)
