### ISSUE TITLE
How to Change imagecrop:gridLeftRightMargin and imagecrop:gridTopBottomMargin in Java Code

### ISSUE THREAD

**Issue by karimabdelhameed** [naver/android-imagecropview#20]
My Question is as in title , I'm not able to change imagecrop:gridLeftRightMargin and imagecrop:gridTopBottomMargin From Java Code !! 

Only From XML ?!! 

How To Solve This ?!!

**Comment by helloyako** [comment]
@karimabdelhameed
I'm sorry I'm late answer
java code doesn't provide setGridLeftRightMagin(gridTopBottomMargin)

I will provide java code in next version

**Comment by helloyako** [comment]
@karimabdelhameed 
I'm done your request.

I will include this spec in v1.2.1. but it's not released.

You can use 1.2.1-snapshot or develop branch source code.

### snapshot version from maven
```
repositories {
    maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
}
dependencies {
   compile 'com.naver.android.helloyako:imagecropview:1.2.1-SNAPSHOT'
}
```

### Java
```java
imageCropView.setGridLeftRightMargin(10); // 10 is dp value
imageCropView.setGridTopBottomMargin(10); // 10 is dp value
```

**Comment by karimabdelhameed** [comment]
Awesome!, 
Thank u very much for ur hard working.

**Comment by helloyako** [comment]
Relase v1.2.1

you can download v1.2.1 in real maven after 2~3 hours

thank you :)
