### ISSUE TITLE
Can it support multiple Scale Type like Center crop, Fit center etc

### ISSUE THREAD

**Issue by AkshayMehta78** [naver/android-imagecropview#23]

**Comment by helloyako** [comment]
I'm sorry It can't support multiple scale tpye

ref.
https://github.com/naver/android-imagecropview/blob/master/imagecropview/src/main/java/com/naver/android/helloyako/imagecrop/view/ImageCropView.java#L197-L203

**Comment by AkshayMehta78** [comment]
What is the main reason why we do not support other scale type?
Is it possible to modify code?

**Comment by helloyako** [comment]
I did not think exact reson now. 
maybe that is because it should do zoom in/out by matrix.

**Comment by AkshayMehta78** [comment]
Okay
