### ISSUE TITLE
Image Preview is white

### ISSUE THREAD

**Issue by eitanshta** [naver/android-imagecropview#3]
When I assign a Bitmap into the ImageCropView some devices show a white background instead of the picture. Do you know something about that problem? 
![11281915_10205484440605297_1410677585_n](https://cloud.githubusercontent.com/assets/9036660/7902205/d75fb78c-07b9-11e5-91b7-cf5520072ecd.jpg)

**Comment by helloyako** [comment]
Do some devices show picture in same source code?
"layout_width" and "layout_height" of ImageCropView must be "match_parent".
is right?

**Comment by eitanshta** [comment]
Yes. Some devices show the picture just the way it should be. I think it's a matter of image size. 
Today im going to check the logs in a device that fails to show the picture and they Ill know more information. 

Thank you for your response.

**Comment by helloyako** [comment]
Oh. I see
please check issue #1 
imageCropView.setImageBitmap(bitmap) -> imageCropView.setImageFilePath(uri.toString())
