### ISSUE TITLE
Crop image with expect size

### ISSUE THREAD

**Issue by huy-lv** [naver/android-imagecropview#32]
Hello, suppose i have a image with size 2000px x 2000px, now i want to crop it to new image with aspect ratio is 16x9 and size is 1600x900. Does your lib support this work :D

**Comment by helloyako** [comment]
@huy-lv 
Hi,
I'm sorry for late answer.
I think... lib will support.

**Comment by huy-lv** [comment]
May i create a pull request :D

**Comment by helloyako** [comment]
PR is always welcome :)

**Comment by helloyako** [comment]
I read this issue again.
I think it's possible now
If it doesn't work, reopen please
