### ISSUE TITLE
Unable to display original image 

### ISSUE THREAD

**Issue by sundariragavan** [naver/android-imagecropview#40]
By default the image is displaying 1:1 aspect ratio. How to display the original image in starting.

**Comment by helloyako** [comment]
Hello, @sundariragavan.
Thank you for contact me

As far as you know, [default aspect ratio](https://github.com/naver/android-imagecropview/blob/develop/imagecropview/src/main/java/com/naver/android/helloyako/imagecrop/view/ImageCropView.java#L60-L61) is 1:1.

I think you can get original image ratio or width and height.

So, you can set ratio when your app start.

```
@Override
public void onCreate(Bundle savedInstanceState) {
...
   int width = originalImage.width;
   int height = originalImage.height;
   imageCropView.setAspectRatio(width, height);
...
}
```
