### ISSUE TITLE
About saveState and restoreState

### ISSUE THREAD

**Issue by MattHPO** [naver/android-imagecropview#41]
Hi,

   Would saveState return a state class? 
Then if we need, we can use the state class to restore the ImageCropView state.
Because I have a view with the gallery, and I need to restore the Image when I edit the image again...

thank you.

**Comment by helloyako** [comment]
Hi

I am sorry to reply late.

Actually, save & restore have some problems.

So I have to fix some problems. and then I will have to check your request.

Unfortunately, I don't have time to fix that bugs. I am sorry
