### ISSUE TITLE
how to disable zoom in and set to zoom out in spesifik action

### ISSUE THREAD

**Issue by yudikarma** [naver/android-imagecropview#47]
i use this library to show image selected from galery, but on multiple select image is enabled, i wan to zoom out image preview (this library) and disable for zoom in (like instagram) please help me. how to do?

**Comment by helloyako** [comment]
Hi, @yudikarma 
First, thank you for using this library.
However, I didn't understand your problem. Can you explain more detail?

**Comment by yudikarma** [comment]
so i create some feature like instagram galery, when user click item photos i show photos in photoview use this library for make that zoomable, but, when user click button for support multiple select photos i dont know how to make that image show cant zoom, what method name for disable zoom ? , actualy i just want to make my photoview user this library can zoom only when user not enable support multiple select photos in my app. btw thanks for awesome library

**Comment by helloyako** [comment]
I'm sorry for late replying.

If you want disable zoom, you should set `setScaleEnabled(false)`.
If you want disable scroll, you should set `setScrollEnabled(false)`

**Comment by yudikarma** [comment]
big thanks @helloyako
