### ISSUE TITLE
#Request need CropInfo model to implement Parcelable

### ISSUE THREAD

**Issue by yudikarma** [naver/android-imagecropview#48]
thanks for awesome library 
 i need to create multiple crop photos, so i create some model for save crop info, but i cant cause CropInfo is not implement parcelable

![Screenshot_2](https://user-images.githubusercontent.com/20062470/64754228-a55dd200-d550-11e9-97aa-85251effe9f0.png)

any idea how i can add CropInfo model to my model with parcelable, may be i can add your library as a Modul to my project, but iam afraid that not get your update

**Comment by helloyako** [comment]
👀
