### ISSUE TITLE
Exception : setParameters failed

### ISSUE THREAD

**Issue by wuandy** [naver/android-imagecropview#9]
I want change the focus area, after I change the value of FOCUS_MAX_BOUND in SquareCameraPreview from 1000 to 1200, then catch the Exception, how to solve it?
(Because the foucs event for large device i.e. 1200x1800, the area is not enough)

**Comment by helloyako** [comment]
@wuandy 
I don't understand your question.
What is focus area, FOCUS_MAX_BOUND and SquareCameraPreview ?

**Comment by wuandy** [comment]
Sorry about this, I I made ​​a mistake, this issue is not here.
Very sorry, and your lib is so useful!

**Comment by helloyako** [comment]
@wuandy 
OK I see.
Thank you for your attention. Have a nice day :)
